### ISSUE TITLE
php7.2.1无法使用？

### ISSUE THREAD

**Issue by henggedaren** [wechatpay-apiv3/wechatpay-php#10]
使用的是7.2.1的版本，composer报错如下： 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - wechatpay/wechatpay 1.0.2 requires guzzlehttp/guzzle ^7.0 -> satisfiable by guzzlehttp/guzzle[7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0, 7.3.0].
    - wechatpay/wechatpay 1.0.3 requires guzzlehttp/guzzle ^7.0 -> satisfiable by guzzlehttp/guzzle[7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0, 7.3.0].
    - wechatpay/wechatpay 1.0.1 requires php ^7.2.5 || ^8.0 -> your PHP version (7.2.1) does not satisfy that requirement.
    - wechatpay/wechatpay 1.0.0 requires php ^7.2.5 || ^8.0 -> your PHP version (7.2.1) does not satisfy that requirement.
    - guzzlehttp/guzzle 7.3.0 requires php ^7.2.5 || ^8.0 -> your PHP version (7.2.1) does not satisfy that requirement.
    - guzzlehttp/guzzle 7.2.0 requires php ^7.2.5 || ^8.0 -> your PHP version (7.2.1) does not satisfy that requirement.
    - guzzlehttp/guzzle 7.1.1 requires php ^7.2.5 -> your PHP version (7.2.1) does not satisfy that requirement.
    - guzzlehttp/guzzle 7.1.0 requires php ^7.2.5 -> your PHP version (7.2.1) does not satisfy that requirement.
    - guzzlehttp/guzzle 7.0.1 requires php ^7.2.5 -> your PHP version (7.2.1) does not satisfy that requirement.
    - guzzlehttp/guzzle 7.0.0 requires php ^7.2.5 -> your PHP version (7.2.1) does not satisfy that requirement.
    - Installation request for wechatpay/wechatpay ^1.0 -> satisfiable by wechatpay/wechatpay[1.0.0, 1.0.1, 1.0.2, 1.0.3].

**Comment by TheNorthMemory** [comment]
`guzzle7` 最低支持的PHP版本是 `7.2.5`，所以你的 `7.2.1` 装不上。

**Comment by TheNorthMemory** [comment]
另外 PHP7.2 都已经EOL了，PHP官方也都停止维护了，建议你升级至`PHP7.4`版本

**Comment by henggedaren** [comment]
> 另外 PHP7.2 都已经EOL了，PHP官方也都停止维护了，建议你升级至`PHP7.4`版本

升级是没有问题的。但是个人觉得最低支持7.0版本比较通用吧，毕竟很多老的项目一时半会没法升级到这么高的版本。

**Comment by TheNorthMemory** [comment]
依赖的关键的加解密功能ext-openssl上的aes-gcm 7.1才添加上，兼容php7.0会比较困难，要做许多适配，另外这个`PHP7.2.5`也是随`guzzle7`限制的，如果是低版本PHP可以尝试用`wechatpay-guzzle-middleware`。

**Comment by henggedaren** [comment]
> 依赖的关键的加解密功能ext-openssl在PHP7.1上才支持aes-gcm；兼容php7.0会比较困难，要做许多适配，另外这个`PHP7.2.5`也是随`guzzle7`限制的，如果是低版本PHP可以尝试用`wechatpay-guzzle-middleware`。

了解了，非常感谢解答！
