### ISSUE TITLE
云开发 Cloud.CloudPay的转账到零钱什么时候考虑加入一下呢

### ISSUE THREAD

**Issue by bym12138** [wechatpay-apiv3/wechatpay-php#100]

**Comment by TheNorthMemory** [comment]
引用自[这里](https://developers.weixin.qq.com/miniprogram/dev/wxcloud/guide/wechatpay/wechatpay.html) 及 [这里](https://developers.weixin.qq.com/miniprogram/dev/wxcloud/reference-sdk-api/open/pay/CloudPay.unifiedOrder.html)

## 微信支付
使用云开发来实现相应的支付功能后，开发者无需关心证书、签名、微信支付服务器端文档，使用简单，代码较少，只需要调用相应的函数即可。此外，因为云开发基于微信私有协议实现，官方通过服务商提供支付接口对接支持，不依赖第三方模块，免去泄漏证书、支付情况等其他敏感信息的风险。同时，云开发还支持云函数接收微信支付进行支付和退款的回调，安全高效。

- 安全：微信私有协议，无证书等信息泄露风险
- 免签名：所有接口免签名 & 直接获取小程序 `wx.requestPayment` 所需参数
- 接收回调：云函数支持接收异步支付结果回调

### 说明
商户在小程序中先调用该接口在微信支付服务后台生成预支付交易单，返回正确的预支付交易后调起支付。

此接口与微信支付原接口（[文档](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1)）的不同点在于：

- 私有安全链路，免证书管理，免签名计算
- 商户号填入 `sub_mch_id` 字段，小程序/公众号 `appid` 填入 `sub_appid` 字段
- 免填写以下字段：`mch_id`、`appid`、`sign`、`sign_type`
- 接口入参和返回值都为 `JSON` 而不是 `XML`

从其流程图上也能看出来有纰漏(比如云函数直接请求微信支付，这是错的)，其背后肯定有一个类似三方、四方的**微信支付服务商应用**在做代理请求及回调通知。从这些公开的资料，无从感知其「私有协议」技术细节及构成，难弄，有能力的欢迎PR.

**Comment by TheNorthMemory** [comment]
引用自[这里](https://developers.weixin.qq.com/miniprogram/dev/wxcloud/guide/wechatpay/wechatpay.html) 及 [这里](https://developers.weixin.qq.com/miniprogram/dev/wxcloud/reference-sdk-api/open/pay/CloudPay.unifiedOrder.html)

## 微信支付
使用云开发来实现相应的支付功能后，开发者无需关心证书、签名、微信支付服务器端文档，使用简单，代码较少，只需要调用相应的函数即可。此外，因为云开发基于微信私有协议实现，官方通过服务商提供支付接口对接支持，不依赖第三方模块，免去泄漏证书、支付情况等其他敏感信息的风险。同时，云开发还支持云函数接收微信支付进行支付和退款的回调，安全高效。

- 安全：微信私有协议，无证书等信息泄露风险
- 免签名：所有接口免签名 & 直接获取小程序 `wx.requestPayment` 所需参数
- 接收回调：云函数支持接收异步支付结果回调

### 说明
商户在小程序中先调用该接口在微信支付服务后台生成预支付交易单，返回正确的预支付交易后调起支付。

此接口与微信支付原接口（[文档](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1)）的不同点在于：

- 私有安全链路，免证书管理，免签名计算
- 商户号填入 `sub_mch_id` 字段，小程序/公众号 `appid` 填入 `sub_appid` 字段
- 免填写以下字段：`mch_id`、`appid`、`sign`、`sign_type`
- 接口入参和返回值都为 `JSON` 而不是 `XML`

从其流程图上也能看出来有纰漏(比如云函数直接请求微信支付，这是错的)，其背后肯定有一个类似三方、四方的**微信支付服务商应用**在做代理请求及回调通知。从这些公开的资料，无从感知其「私有协议」技术细节及构成，难弄，有能力的欢迎PR.
