### ISSUE TITLE
提问，Rsa::verify的问题

### ISSUE THREAD

**Issue by MichonneHsu** [wechatpay-apiv3/wechatpay-php#101]
### 运行环境

```markdown
- OS:AliOS
- PHP:8.0.15
- wechatpay-php:latest
```

### 描述你的问题现象

```php
   $wechat_params=[
            'wechatpay_timestamp'=>$wechatpay_timestamp,
            'wechatpay_signature'=>$wechatpay_signature,
            'wechatpay_serial'=>$wechatpay_serial,
            'wechatpa_nonce'=>$wechatpa_nonce
        ];
        $inBody=json_encode([
            'id'=>$id,
            'create_time'=>$create_time,
            'resource_type'=>$resource_type,
            'event_type'=>$event_type,
            'summary'=>$summary,
            'resource'=>$resource
        ]);
        $v=Util::verify($wechat_params,$inBody);

```
verify代码
```php
   $message=Formatter::joinedByLineFeed($inWechatpayTimestamp, $inWechatpayNonce, $inBody);
   $verifiedStatus =Rsa::verify($message,$inWechatpaySignature,$platformPublicKeyInstance);
```
我在5分钟内去验证是否有效，为什么老是`$verifiedStatus`返回`false` ?

**Comment by IFromHell** [comment]
<img width="870" alt="image" src="https://user-images.githubusercontent.com/30306293/181879357-f5d2ec6c-e760-4309-b371-0281ba16a5a4.png">

之前我也遇到了这个问题，研究大半天之后，原来是`$inWechatpayTimestamp`必须是整数类型。

**Comment by MikeMaldini** [comment]
> <img alt="image" width="870" src="https://user-images.githubusercontent.com/30306293/181879357-f5d2ec6c-e760-4309-b371-0281ba16a5a4.png">
> 
> 之前我也遇到了这个问题，研究大半天之后，原来是`$inWechatpayTimestamp`必须是整数类型。

但我这还是不通

**Comment by TheNorthMemory** [comment]
```php
$inBody=json_encode
```
这个就不是原始传过来的`JSON`字符串，PHP [json_encode](https://www.php.net/manual/zh/function.json-encode.php) 默认的 `int $flags = 0` 意味着，当原始待编码的字符串含 `UNICODE`, `SLASH`， 此函数会转义成`utf-8`编码格式，例如：

```php
$a = ['c' => 'http://x', 'k' => '测试'];
print_r(json_enocde($a));
```

打印为：

```json
{"c":"http:\/\/x","k":"\u6d4b\u8bd5"}
```

而原始推送的可能是：

```json
{"c":"http://x","k":"测试"}
```

你怎么校验上述自行编码的字符串，都会返回`false`。
