### ISSUE TITLE
支持PHP7.0版本吗？

### ISSUE THREAD

**Issue by renkun-cook** [wechatpay-apiv3/wechatpay-php#106]
### 运行环境

```Markdown
- OS:
- PHP:
- wechatpay-php:
```

**Comment by renkun-cook** [comment]
支持PHP7.0版本吗？

**Comment by TheNorthMemory** [comment]
> 支持PHP7.0版本吗？

因内置的openssl自7.1才开始支持`AesGcm`，顾不考虑兼容PHP7.0，更多可见 https://github.com/wechatpay-apiv3/wechatpay-php/issues/86

**Comment by renkun-cook** [comment]
生产环境是PHP7.0的了，有可以用的sdk吗？

**Comment by TheNorthMemory** [comment]
> 生产环境是PHP7.0的了，有可以用的sdk吗？

https://github.com/wechatpay-apiv3/wechatpay-php/issues/86 有答案，需要你自行处理了。
