### ISSUE TITLE
初始化参数`certs`键值对参数校验时为什么不能含商户证书序列号`merchantSerialNumber`

### ISSUE THREAD

**Issue by guoyuanchang** [wechatpay-apiv3/wechatpay-php#108]
### 运行环境

```Markdown
- OS:centos
- PHP:7.4
- wechatpay-php: src/ClientJsonTrait.php:222

if (array_key_exists($config['serial'], $config['certs'])) {
            throw new Exception\InvalidArgumentException(sprintf(
                Exception\ERR_INIT_CERTS_EXCLUDE_MCHSERIAL, implode(',', array_keys($config['certs'])), $config['serial']
            ));
        }

这里应该是写反了，导致参数校验不通过。应该在前面加上 ！。
```

**Comment by TheNorthMemory** [comment]
参考 #82 ，是你给错「平台证书」键值对了，SDK强校验了这种逻辑错误。

**Comment by guoyuanchang** [comment]
<img width="975" alt="image" src="https://user-images.githubusercontent.com/10287082/195352836-726f758f-0e59-4ae5-b6c0-7e4d77fb0073.png">
我这里是参照你的示例写的。

传的参数中，$merchantCertificateSerial 和 $platformCertificateSerial值是相同的，然后就被上面那个地方拦截了。

**Comment by TheNorthMemory** [comment]
`composer v3-certificates -k ${apiV3key} -m ${mchId} -f ${mchPrivateKeyFilePath} -s ${mchSerialNo} -o ${outputFilePath}`

先用composer 命令下载平台证书，用法help `composer v3-certificates`

**Comment by TheNorthMemory** [comment]
ℹ️ 你需要先手工 [下载平台证书](https://github.com/wechatpay-apiv3/wechatpay-php#%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E5%B9%B3%E5%8F%B0%E8%AF%81%E4%B9%A6) 才能使用 SDK 发起请求。
