### ISSUE TITLE
UriTemplate guzzle 版本<7.0存在， >=7.0没有UriTemplate，导致报错

### ISSUE THREAD

**Issue by halx99** [wechatpay-apiv3/wechatpay-php#113]
### 运行环境

```Markdown
- OS:Windows 11
- PHP:7.4.33
- wechatpay-php:master/1.4.8
```

### 描述你的问题现象

两个问题: 
1. guzzle库 >=7.0没有`UriTemplate`，导致报错
2. ClientDecorator.php request和requestAsync里报错，尝试以静态方式调用`UriTemplate`的对象方法`expand`

问题复现：readme里下载证书代码

### 相关链接
- https://github.com/guzzle/guzzle/pull/2440

**Comment by TheNorthMemory** [comment]
在你的项目下，执行一下`composer info`命令，应能打印出类似如下依赖：

```
guzzlehttp/uri-template            v1.0.1  A polyfill class for uri_template of PHP
```

对应的项目是： https://github.com/guzzle/uri-template

**Comment by halx99** [comment]
> 在你的项目下，执行一下`composer info`命令，应能打印出类似如下依赖：
> 
> ```
> guzzlehttp/uri-template            v1.0.1  A polyfill class for uri_template of PHP
> ```
> 
> 对应的项目是： https://github.com/guzzle/uri-template

谢谢，解决了。
