### ISSUE TITLE
How to Test Payment with Mini Program

### ISSUE THREAD

**Issue by shoaib039** [wechatpay-apiv3/wechatpay-php#117]
### 运行环境

```Markdown
- OS: Wechat MiniProgram
- PHP: Laravel 8
- wechatpay-php: MiniProgram

Hi, can i use this API for Wechat MiniProgram and Also how to test payment like sandbox not actual payment. I try to find a lot but i didn't found any articles for test wechat pay with MiniProgram.

Waiting for your reply.

Thank you.
```

**Comment by TheNorthMemory** [comment]
So far as I known, there's no sandbox environment in the wechatpay development acturally even if there was a XDC entrypoint which was also dependency on the real merchant account.

So, the confusion should be "How to Development with the WeChat MiniProgram and WeChat Pay". Main purpose steps should be:

1. Registry a real MiniProgram account and then verification by one of 3rd administrative company;
2. Registry a real WeChat Pay merchant account through the MiniProgram's MP interface and then verification;
3. Following the official development guideline, setup the environment of the WeChat Pay account;
4. Implement the applicaiton with one of the SDK with step1(appid), step2(mchid) accounts;

Then, enjoy and happy to join the WeChat MiniProgram world.
