### ISSUE TITLE
API V3的作用

### ISSUE THREAD

**Issue by haotianyuhuang** [wechatpay-apiv3/wechatpay-php#120]
### 运行环境

```Markdown
- OS:
- PHP:
- wechatpay-php:
```

### 描述你的问题现象

它的意义是否在于对回调的付款详情进行解密？

**Comment by TheNorthMemory** [comment]
## [关于API v3](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay-1.shtml)

为了在保证支付安全的前提下，带给商户简单、一致且易用的开发体验，我们推出了全新的微信支付API v3。

相较于之前的微信支付API，主要区别是：

- 遵循统一的REST的设计风格
- 使用JSON作为数据交互的格式，不再使用XML
- 使用基于非对称密钥的SHA256-RSA的数字签名算法，不再使用MD5或HMAC-SHA256
- 不再要求携带HTTPS客户端证书（仅需携带证书序列号）
- 使用AES-256-GCM，对回调中的关键信息进行加密保护

**Comment by metooweb** [comment]
> ## [关于API v3](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay-1.shtml)
> 为了在保证支付安全的前提下，带给商户简单、一致且易用的开发体验，我们推出了全新的微信支付API v3。
> 
> 相较于之前的微信支付API，主要区别是：
> 
> * 遵循统一的REST的设计风格
> * 使用JSON作为数据交互的格式，不再使用XML
> * 使用基于非对称密钥的SHA256-RSA的数字签名算法，不再使用MD5或HMAC-SHA256
> * 不再要求携带HTTPS客户端证书（仅需携带证书序列号）
> * 使用AES-256-GCM，对回调中的关键信息进行加密保护

与其研究茴字有几个写法，不如优化开发者体验，修复开发者提出的BUG 🤡
