### ISSUE TITLE
请问境外支付如何使用apihk域名？

### ISSUE THREAD

**Issue by garygwl** [wechatpay-apiv3/wechatpay-php#124]
### 运行环境

```Markdown
- OS:
- PHP:
- wechatpay-php:
```

**Comment by TheNorthMemory** [comment]
初始化的时候，给`base_uri`参数，例如证书下载工具支持的一样：

https://github.com/wechatpay-apiv3/wechatpay-php/blob/fbe8d7c2b3b367e42bf98caa0cce582b3205d427/bin/CertificateDownloader.php#L175-L176

或者不增初始化参数，在每请求的`options`里增加`base_uri`也同样效果，例如：

https://github.com/TheNorthMemory/wechatpay-openapi/blob/master/src/V3/Global_/Transactions/Native.php#L17-L68

https://github.com/TheNorthMemory/wechatpay-openapi/blob/d1bb855c160fb35754a88516edad062593e698bb/src/V3/Settle/Settlements.php#L17-L27
