### ISSUE TITLE
图片上传只有本地，没有网络图片的示例吗

### ISSUE THREAD

**Issue by ken678** [wechatpay-apiv3/wechatpay-php#135]
```Markdown
图片上传只有本地，没有网络图片的示例吗
```

建议MediaUtil.php的$filepath增加判断是否为网络图片

**Comment by ken678** [comment]
对于直传oss的，本地是没有图片的  示例都是本地图片 看代码也没有支持网络图片 MediaUtil.php只要做下兼容

**Comment by TheNorthMemory** [comment]
能get到你说的，直接上送网络图片URL，微信小程序有类似的[设计](https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/sec-center/sec-check/mediaCheckAsync.html)，其上送的payload与微信支付API要求的不完全一致。

本就微信支付API来说，其要求是`multipart/form-data`传输，混合二进制图片内容及必要的二进制内容摘要，网络图片URL也是需要有个“下载”到本地的过程才能匹配API传输协议。

如你有成熟方案，欢迎提PR增强。

**Comment by TheNorthMemory** [comment]
如有PR可引用
