### ISSUE TITLE
SDK中自动验签对探测流量没有进行特殊处理

### ISSUE THREAD

**Issue by BraisedFish** [wechatpay-apiv3/wechatpay-php#139]
### 运行环境

```Markdown
- OS: alpine 3.18
- PHP: 8.3
- wechatpay-php: 1.4.10
```

### 描述你的问题现象

使用下载账单接口过程中，SDK 会对响应头自动验签，但是 Wechatpay-Signature 会出现微信支付发出探测流量的情况使验签失败。这样的失败现在会直接抛出请求异常 \GuzzleHttp\Exception\RequestException，导致本应该正常执行的程序失败。
发生在 \WeChatPay\ClientJsonTrait::assertSuccessfulResponse
>  
            try {
                $verified = Crypto\Rsa::verify(
                    Formatter::response(
                        $timestamp,
                        $nonce,
                        $isOverseas ? static::digestBody($response) : static::body($response)
                    ),
                    $signature, $certs[$serial]
                );
            } catch (\Exception $exception) {}
            if ($verified === false) {
                throw new RequestException(sprintf(
                    Exception\WeChatPayException::EV3_RES_HEADER_SIGNATURE_DIGEST,
                    $timestamp, $nonce, $signature, $serial
                ), $request, $response, $exception ?? null);
            }
希望可以规避这种异常出现，不要使正常的程序被中断。

**Comment by TheNorthMemory** [comment]
「探测流量」是指 [webhook回调](https://pay.weixin.qq.com/docs/merchant/development/verify-signature/verify-signature-tool.html) 的 `WECHATPAY/SIGNTEST/` 流量吗？

**Comment by TheNorthMemory** [comment]
> > 「探测流量」是指 [webhook回调](https://pay.weixin.qq.com/docs/merchant/development/verify-signature/verify-signature-tool.html) 的 `WECHATPAY/SIGNTEST/` 流量吗？
> 
> 是的。我们获取到请求失败的响应，其中响应头 Wechatpay-Signature 中发现带有 `WECHATPAY/SIGNTEST/`，我们理解符合文档中对「探测流量」的描述

对于「探测流量」的处理，官方是建议**不要做特殊处理**，这样更符合 **失败也是一种预期** 的探测设定。

从顶楼贴的代码来分析，你可能是把作为**客户端**自动验证请求返回文本结果的代码，应用在了**服务端**响应商户平台通知请求的场景中了，虽然处理逻辑很相像，建议用 try catch 语句对异常捕获以应对 **失败也是一种预期** 这种设定。

**Comment by BraisedFish** [comment]
> > > 「探测流量」是指 [webhook回调](https://pay.weixin.qq.com/docs/merchant/development/verify-signature/verify-signature-tool.html) 的 `WECHATPAY/SIGNTEST/` 流量吗？
> > 
> > 
> > 是的。我们获取到请求失败的响应，其中响应头 Wechatpay-Signature 中发现带有 `WECHATPAY/SIGNTEST/`，我们理解符合文档中对「探测流量」的描述
> 
> 对于「探测流量」的处理，官方是建议**不要做特殊处理**，这样更符合 **失败也是一种预期** 的探测设定。
> 
> 从顶楼贴的代码来分析，你可能是把作为**客户端**自动验证请求返回文本结果的代码，应用在了**服务端**响应商户平台通知请求的场景中了，虽然处理逻辑很相像，建议用 try catch 语句对异常捕获以应对 **失败也是一种预期** 这种设定。

顶楼的代码是 SDK 里面的。我明白您的意思了，谢谢
