### ISSUE TITLE
这个是Cannot found the serial  是什么意思呢

### ISSUE THREAD

**Issue by Maplejay** [wechatpay-apiv3/wechatpay-php#14]
![image](https://user-images.githubusercontent.com/17807750/125589596-115747fb-3dfb-4386-920f-30eb8caabc76.png)

**Comment by TheNorthMemory** [comment]
`certs[$serial_number => #resource]` 为通过下载工具下载的平台证书key/value键值对，键为平台证书序列号，值为平台证书pem格式的纯字符串或者文件resource格式

**Comment by TheNorthMemory** [comment]
先用平台证书下载器，下载一下`平台证书`吧
