### ISSUE TITLE
我还是过来咨询下 DEMO吧~

### ISSUE THREAD

**Issue by youfeed** [wechatpay-apiv3/wechatpay-php#141]
### 运行环境

```Markdown
- OS:
- PHP:
- wechatpay-php:
```

### 描述你的问题现象

这种是为啥
``` php
@['apiclient_key'=>$apiclient_key,'public_key'=>$public_key,'serial'=>$serial,'platform_serial'=>$platform_serial] = $merch = Config("payment.$merchantId");
 
        // 「商户API私钥」会用来生成请求的签名
        $merchantPrivateKeyInstance = Rsa::from($apiclient_key, Rsa::KEY_TYPE_PRIVATE);
        // 「商户API证书」的「证书序列号」
        // 从本地文件中加载「微信支付平台证书」或者「微信支付平台公钥」，用来验证微信支付应答的签名
        $platformPublicKeyInstance = Rsa::from($public_key, Rsa::KEY_TYPE_PUBLIC);
        // 「微信支付平台证书」的「证书序列号」或者是「微信支付平台公钥ID」
        // 「平台证书序列号」及/或「平台公钥ID」可以从 商户平台 -> 账户中心 -> API安全 直接查询到
        $platformCertificateSerialOrPublicKeyId = $platform_serial;
        // 构造一个 APIv3 客户端实例
        $instance = Builder::factory([
            'mchid'      => $merchantId,
            'serial'     => $serial,
            'privateKey' => $merchantPrivateKeyInstance,
            'certs'      => [
                $platform_serial => $platformPublicKeyInstance,
            ],
        ]);
    
        // 发送请求
        $resp = $instance->chain('v3/certificates')->get(
            /** @see https://docs.guzzlephp.org/en/stable/request-options.html#debug */
            // ['debug' => true] // 调试模式
        );
        $body = (string)$resp->getBody();
        return success([get_class_methods($instance),$platform_serial,$serial,$merchantId],'233');
```

请求正确发出去了，但是无法验证
![image](https://github.com/user-attachments/assets/e118d89b-2ea2-4d6e-8668-7499e5a31b35)

**Comment by youfeed** [comment]
是微信平台证书不对的问题：
大家自己去下载一下：CertificateDownloader.jar 工具：
进到和他同级的目录去 按照参数填写进去会自动保存，
```
java -jar CertificateDownloader.jar -k PrlbgF6S**** -m 16818**** -f ./apiclient_key.pem -s 7C9C6954D13014196807****** -o ./
```
得到：`wechatpay_5D7EB30F544EF9BA68945B61419EBA6A47C638B5.pem`文件：
```
-----BEGIN CERTIFICATE-----
MIIEFDCCAvygAwIBAgIUXX6zD1RO+bpolFthQZ66akfGOLUwDQYJKoZIhvcNAQEL
BQAwXjELMAkGA1UEBhMCQ04xEzARBgNVBAoTClRlbnBheS5jb20xHTAbBgNVBAsT
FFRlbnBheS5jb20gQ0EgQ2VudGVyMRswGQYDVQQDExJUZW5wYXkuY29tIFJvb3Qg
Q0EwHhcNMjQxMTA3MTEwOTQyWhcNMjkxMTA2MTEwOTQyWjBuMRgwFgYDVQQDDA9U
ZW5wYXkuY29tIHNpZ24xEzARBgNVBAoMClRlbnBheS5jb20xHTAbBgNVBAsMFFRl
bnBheS5jb20gQ0EgQ2VudGVyMQswCQYDVQQGEwJDTjERMA8GA1UEBwwIU2hlblpo
ZW4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD6L/32JoToXQPDURXC
pd4wAxnKoBCdojBLSUT+YOLSJo9WF6f8x1mmvakQx6kKoiX+daUYo3vqTJKa/q4d
pLN5cY2GGl3mmD8fKru5xtCPUYvCh3dc0SZ61qNT7KIlP3Qq97CQTaj7nKr66dOy
jmcVoY4HA2RbgsTIBCjwIP/aUEslscSYwRtwJe0rhZNKH2Z8LntKRsPZkDqjr+UX
oiAU1tZUXFZexX3khWtSTIRSljErPaZ1cPTgBeecenq0Glym44ekJvUJDp7Tgva8
2jAtq2lfksD3VbgUSl+PLekN9q2eitzOJI3f8IW1awFYTT6GouibJZMaqDza0pxO
dAXxAgMBAAGjgbkwgbYwCQYDVR0TBAIwADALBgNVHQ8EBAMCA/gwgZsGA1UdHwSB
kzCBkDCBjaCBiqCBh4aBhGh0dHA6Ly9ldmNhLml0cnVzLmNvbS5jbi9wdWJsaWMv
aXRydXNjcmw/Q0E9MUJENDIyMEU1MERCQzA0QjA2QUQzOTc1NDk4NDZDMDFDM0U4
RUJEMiZzZz1IQUNDNDcxQjY1NDIyRTEyQjI3QTlEMzNBODdBRDFDREY1OTI2RTE0
MDM3MTANBgkqhkiG9w0BAQsFAAOCAQEAUclKlv7L+C1l8KadeUwdrqtaPPGN0tYV
MBrG0q9HGbi3gjEAisXupIokDFdGbhO0A3Wf7opVOnOic02HGipZMibscS3JzaZG
MqDX8+2DSrKSPLSdx7Mb4wa44qvon28kDeXLw30DXtmCm9+nAL+oIrzztOPU6Sr6
m3hugFWhmTLWIHReM3vucHoeq5YwCGK3gE/tUEzBya2a+4HQtCqAnZ+5F6seyCTC
WHzQKvM4lxpayrnHKN+15v4d08UUVX0RCRJxv3O6J0VbL5DpZOFvhKW6xWGO1Q8b
DkXEetMOOCoDbs3iwCz2MWG4z+7VcMPSLOGXqnIT5P7dK6Cm/UHAPA==
-----END CERTIFICATE-----
```


### 最后说一下：微信这个问题很多年了，死都解决：每次都得装下`JAVA`，其实完全可以坐在微信首次获取`apiclient_key.pem`那个工具里面得：缺少像支付宝那种人情味.

**Comment by TheNorthMemory** [comment]
[本包在 `1.0` 版本的时候即提供了与Java版参数语义一致的下载方案(并且原生支持应答验签功能)，使用`composer`命令，像安装依赖包一样下载平台证书文件。](https://wechatpay.im/guide/)

> 执行如下命令：

```
composer exec CertificateDownloader.php -- \
-k APIv3KeyString \
-m merchantId \
-s merchantCertificateSerial \
-f /path/to/merchant/apiclient_key.pem \
-o .
```
提供正确的`APIv3密钥`、`商户号`、`商户API证书序列号`、`商户API私钥文件地址`，执行后，平台证书即下载成功

**Comment by youfeed** [comment]
// 构造一个 APIv3 客户端实例
        $instance = Builder::factory([
            'mchid'      => $merchantId,
            'serial'     => $serial,
            'privateKey' => $merchantPrivateKeyInstance,
            'certs'      => [
                $platform_serial => $platformPublicKeyInstance,
            ],
        ]);
        ### 有参数可以关闭验证吗？

**Comment by TheNorthMemory** [comment]
> // 构造一个 APIv3 客户端实例 $instance = Builder::factory([ 'mchid' => $merchantId, 'serial' => $serial, 'privateKey' => $merchantPrivateKeyInstance, 'certs' => [ $platform_serial => $platformPublicKeyInstance, ], ]); ### 有参数可以关闭验证吗？

关闭验证属于「不推荐」用法，无法保证你取得的数据安全可信性

**Comment by youfeed** [comment]
关闭验证 确实是不推荐的，如果提供这个功能大部分人都会开启，现在是必须要自己维护一个 "平台证书" 列表,
后续开发建议
1. Builder::factory certs==false 则不验证(风险自负 仅用于更新平台证书时，短暂开启)
2. Builder::factory certs==Array 用户自己维护的证书链列表
3.1 Builder::factory certs==true 库维护的证书链列表
3.2 库-日志+证书列表 (PHP-FPM 被动更新证书) 返回请求证书序列号不在 就获取一次平台证书"

**Comment by TheNorthMemory** [comment]
> [!NOTE]
> 2024年Q3，微信支付官方开启了「平台公钥」平替「平台证书」方案，初始化所需的参数仅需配置上 **平台公钥ID** 及 **平台公钥** 即完全兼容支持，CLI/API下载 **平台证书** 已不是一个必要步骤，可略过。
> **平台公钥ID** 及 **平台公钥** 均可在 [微信支付商户平台](https://pay.weixin.qq.com/) -> 账户中心 -> API安全 查看及/或下载。

实质上，「平台证书」已经是过去式了，不存在**自动下载**的前置因素了。

另外 certs 是个数组，是提供了能力动态调整数组里的元素的，这部分可以参阅内置的下载工具「是先有蛋还是先有鸡」的解题思路，上层应用完全有能力自己管理 certs 的数据「动态」更新。

日志能力是 Guzzle 的原生能力，如何在 `handler` 上无感增加日志记录输出，可参阅 Guzzle 文档。

**Comment by youfeed** [comment]
我看到了：`[API安全]/平台证书管理`
当前证书
序列号 5D7EB30F544EF9BA6B5
有效期 2024/11/7 ~ 2029/11/6
这个证书ID以及内容，是长期的 不会变化对吧，
$instance = Builder::factory==certs
['5D7EB30F544EF9BA6B5'=>接口下载并解密] 这样就行了是吧；
验证微信返回 里面也有个 serial_no 他二个是成对出现的；是一样的吗？
这个地方：就没弄懂，

**Comment by TheNorthMemory** [comment]
> 我看到了：`[API安全]/平台证书管理` 当前证书 序列号 5D7EB30F544EF9BA6B5 有效期 2024/11/7 ~ 2029/11/6 这个证书ID以及内容，是长期的 不会变化对吧， $instance = Builder::factory==certs ['5D7EB30F544EF9BA6B5'=>接口下载并解密] 这样就行了是吧； 验证微信返回 里面也有个 serial_no 他二个是成对出现的；是一样的吗？ 这个地方：就没弄懂，

建议阅读：[平台证书简介](https://pay.weixin.qq.com/docs/merchant/development/interface-rules/wechatpay-certificates.html) [平台证书更换操作指引](https://pay.weixin.qq.com/docs/merchant/development/interface-rules/wechatpay-certificates-rotation.html)  [新商户号调用下载平台证书API报错处理指引](https://developers.weixin.qq.com/community/develop/doc/000686f7ad8710f2d252e11f266400)

**Comment by youfeed** [comment]
感谢帮助~ 爱你~😘
