### ISSUE TITLE
Builder::factory 参数和支付类型问题

### ISSUE THREAD

**Issue by MichonneHsu** [wechatpay-apiv3/wechatpay-php#15]
`'certs' => [
        // 可由内置的平台证书下载器 `./bin/CertificateDownloader.php` 生成
        'YYYYYYYYYY' => PemUtil::loadCertificate('/path/to/wechatpay/cert.pem')
    ],`

这里的Y是个什么？我填入序列号报错，不填没错。
还有个问题
支付只有native类型?

**Comment by TheNorthMemory** [comment]
初始化字典说明如下：

- `mchid` 为你的`商户号`，一般是10字节纯数字
- `serial` 为你的`商户证书序列号`，一般是40字节字符串
- `privateKey` 为你的`商户API私钥`，一般是通过官方证书生成工具生成的文件名是`apiclient_key.pem`文件，支持纯字符串或者文件`resource`格式
- `certs[$serial_number => #resource]` 为通过下载工具下载的平台证书`key/value`键值对，键为`平台证书序列号`，值为`平台证书`pem格式的纯字符串或者文件`resource`格式

**Comment by joker02161** [comment]
请问 服务商也是这样么 [‘mchid’=>服务商sp_mchid, ‘serial ’=> 服务商证书序列号, ‘privatKey ’=>服务商私钥,certs[平台证书序列号=> #平台证书内容] ] 这样么？
