### ISSUE TITLE
传递正常的参数，提示参数类型格式错误

### ISSUE THREAD

**Issue by sentangle** [wechatpay-apiv3/wechatpay-php#18]
php错误提示很明显，参数格式有问题，但是知道具体那个参数问题？

 ### json数据

{"organization_type":"2401","id_card_info":{"id_card_copy":"4AwYFk-PxXLINImzbD0Gmv5zOL7V3d_bfT6zQeXUc5L88hvsMYfOqybCZhzTHS4VdBWt_chQndK4PXugzXLOaEUhDrmhr7ISmvmGRlewzS0","id_card_national":"4AwYFk-PxXLINImzbD0GmjXLkUAjf1WjOchmdltYk0oef0yO_DCtRplp8nZnf2NRvWvcRJLkI1jN8MK4A762IWe-mC7osKVI6gb2btRvz_k","id_card_name":"lTTvIKywa8Ksm+ntTyMtgfawrqoKUhVDDRrBZXgbV596X9XWgbu7qstmrMbdmQh6Wm3rzrhfDJISjzFLivFGSK544qwblV8zrm7z/q2//KNn3v+9uQh4gnrHb1p2kGoOz/L5J3t7wkkvf9JTlWTFDmTXJcpqcTV1UyAL2j5Ad3XKa/h8c2H3cB0sAkmvZU2cbACbitgTn50v7ya16ZiqISnP6MDJEgcJiLXrrPGa5tATPFfn3NmSDRgMvZxTlwhOeR7TSX1/gPLinAR+pnkfbDmsvM3yebCehIrvmatxt6gnYEiljzZZ0mJJZWFvh4GRl7XpFlIdMIQcVRM4Vza8tA==","id_card_number":"N8zqykRXema++232pXNgb3S2ImddBj+7QXI+pMPYI8jHbHEkDdiXQcsvyJMUotxYXg7+1zK2U7uSvaDMR1ORvj33pXOSrp4B5kUzIdMjZb7L1nFiygsGeHWFJp5V2RfJ9nXXbKj/82JdhMb4sUsv1LTjgx2UzIG4qbwWQSFGeLjRKT86wRsKrNb86eF2Xvu8LMZuw/AyGGfNEEVzRuHfDtmxq7hreuJztEXDTu+Qxtyl9X1+jovGeS6TcWziGm92G2QllarsCXSfpzfAnSPNx4uDka+JTZDE1FNX8S8ujrmowaDq2NAe/zyWfqLg1JNIK2fWdsoQUCiUWcf/QZATNw==","id_card_valid_time":"2036-03-13"},"contact_info":{"contact_type":"65","contact_name":"lVOHUP2Oc2JwKk3JjYQwE/G9l58bE7BilcgjZ3tLEyB07IotvLQ42DLj/q3PkaQtEF/HyGP6AAfPTdhOpCKW1X2rqjbO4JMTXhj75yNtUWgnBqMQ/+esgzh6gIBITudMhT7drsggqj4pBsEkg1msLaJBju/mYxRFrWcghwpNg2me9oMoNI28j1my9TDiivItKOhT+YRntwopLQb8qtqnoUMNFwpvnXuipjjj7I24flawmwKr+eD7wPYO/cc341PZV/dhcdZ8yjAl+HS3HqvZ76zfC+RyozOzk8trGfqnQNebjRedalW5q8vbnmEV60z6cjgwIHzVBSHqO7eS9h2QRA==","contact_id_card_number":"JzKxKbgzgtMfQVmSSkJ8hcjqXJXnBZBJv0ji0kMr3atNLhciy8U/XhgQYamZve3/92Az98mg0MmJ+9xuyzkORTneLY6THKAbBpl+UMu7I4Mc/nCcYlntv6n3kuRywvWB0FMYIADrdTElsGRgh7iUeo3qlKRFH/2jJT5mlNkguC6TAt0ULJyMLVycxoEL5ggKzvMtt6AN4AYJWLmZJY7ZEkhS86z99zjuXdrUTikGfFBhTimK1O4/kGV9SOGzJguajVZaPIOU4WmGOuALpCEFHQoIz1R+N7ZFqk1L3cvdtfxxtfIBGleXl91CKm8BdAXcNVonhwFDodRQWr4QUWqRig==","mobile_phone":"eQa4SIQ2XJW68Kya4AFg5RNrLvwZf9hJCBerx99LZL0KxBjqZb1nP0l8JtWe8mzSJZgYM9i7qRWdhbtzXm8I5fxU8bCmBZX0ODyy6FAKPSacDtfQLLHpGW5Q/j07gimx5hq5n4x/vLbr3i3yKTOm1lbCeiDOOltDxAhnRoHI6pu61BBNwrD7Y8k9CKwTWCccRcGLJBnD9Wj/RYu2c2MFGMZitw/kCJk4fyuSzTC6vMMb2qpCMvWljgTn3LgCe4YX6ukJm2vf4C684XzsKL8qCzgMM4lj7QqTEVakU7uqonAuPnu4G4mzhlmcBiG4U80FILrv0UYjmuV9FxlJWVj5iQ=="},"need_account_info":false,"sales_scene_info":{"store_name":"测试店铺信息","store_url":"http://test.xxx.com/test.php"},"merchant_shortname":"大红料","out_request_no":"20210721171352"}

### 报错信息

![image](https://user-images.githubusercontent.com/6250675/126464953-07ed2957-b186-4b8a-9437-42c38bd8aef6.png)

### 页面代码
![image](https://user-images.githubusercontent.com/6250675/126464840-cee9576f-a0a1-41f0-a3af-bf836befccb5.png)

**Comment by TheNorthMemory** [comment]
不建议直接`'body' => $bodyJson`， 试试换成 `'json' => $json`

**Comment by sentangle** [comment]
### 更换写法后 提示相同错误
![image](https://user-images.githubusercontent.com/6250675/126468181-c2314698-f24e-4ed1-b2e5-d07f9971bae3.png)

### 项目目录结构
![image](https://user-images.githubusercontent.com/6250675/126468789-9ccb9b0c-06e7-46b9-9250-8749fe53aec0.png)

###请问大佬，使用该sdk还有推荐详细文档？
目前参考官网开发文档  https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter7_1_1.shtml

**Comment by TheNorthMemory** [comment]
```json
{
  "organization_type": "2401",
  "id_card_info": {
    "id_card_copy": "4AwYFk-PxXLINImzbD0Gmv5zOL7V3d_bfT6zQeXUc5L88hvsMYfOqybCZhzTHS4VdBWt_chQndK4PXugzXLOaEUhDrmhr7ISmvmGRlewzS0",
    "id_card_national": "4AwYFk-PxXLINImzbD0GmjXLkUAjf1WjOchmdltYk0oef0yO_DCtRplp8nZnf2NRvWvcRJLkI1jN8MK4A762IWe-mC7osKVI6gb2btRvz_k",
    "id_card_name": "lTTvIKywa8Ksm+ntTyMtgfawrqoKUhVDDRrBZXgbV596X9XWgbu7qstmrMbdmQh6Wm3rzrhfDJISjzFLivFGSK544qwblV8zrm7z/q2//KNn3v+9uQh4gnrHb1p2kGoOz/L5J3t7wkkvf9JTlWTFDmTXJcpqcTV1UyAL2j5Ad3XKa/h8c2H3cB0sAkmvZU2cbACbitgTn50v7ya16ZiqISnP6MDJEgcJiLXrrPGa5tATPFfn3NmSDRgMvZxTlwhOeR7TSX1/gPLinAR+pnkfbDmsvM3yebCehIrvmatxt6gnYEiljzZZ0mJJZWFvh4GRl7XpFlIdMIQcVRM4Vza8tA==",
    "id_card_number": "N8zqykRXema++232pXNgb3S2ImddBj+7QXI+pMPYI8jHbHEkDdiXQcsvyJMUotxYXg7+1zK2U7uSvaDMR1ORvj33pXOSrp4B5kUzIdMjZb7L1nFiygsGeHWFJp5V2RfJ9nXXbKj/82JdhMb4sUsv1LTjgx2UzIG4qbwWQSFGeLjRKT86wRsKrNb86eF2Xvu8LMZuw/AyGGfNEEVzRuHfDtmxq7hreuJztEXDTu+Qxtyl9X1+jovGeS6TcWziGm92G2QllarsCXSfpzfAnSPNx4uDka+JTZDE1FNX8S8ujrmowaDq2NAe/zyWfqLg1JNIK2fWdsoQUCiUWcf/QZATNw==",
    "id_card_valid_time": "2036-03-13"
  },
  "contact_info": {
    "contact_type": "65",
    "contact_name": "lVOHUP2Oc2JwKk3JjYQwE/G9l58bE7BilcgjZ3tLEyB07IotvLQ42DLj/q3PkaQtEF/HyGP6AAfPTdhOpCKW1X2rqjbO4JMTXhj75yNtUWgnBqMQ/+esgzh6gIBITudMhT7drsggqj4pBsEkg1msLaJBju/mYxRFrWcghwpNg2me9oMoNI28j1my9TDiivItKOhT+YRntwopLQb8qtqnoUMNFwpvnXuipjjj7I24flawmwKr+eD7wPYO/cc341PZV/dhcdZ8yjAl+HS3HqvZ76zfC+RyozOzk8trGfqnQNebjRedalW5q8vbnmEV60z6cjgwIHzVBSHqO7eS9h2QRA==",
    "contact_id_card_number": "JzKxKbgzgtMfQVmSSkJ8hcjqXJXnBZBJv0ji0kMr3atNLhciy8U/XhgQYamZve3/92Az98mg0MmJ+9xuyzkORTneLY6THKAbBpl+UMu7I4Mc/nCcYlntv6n3kuRywvWB0FMYIADrdTElsGRgh7iUeo3qlKRFH/2jJT5mlNkguC6TAt0ULJyMLVycxoEL5ggKzvMtt6AN4AYJWLmZJY7ZEkhS86z99zjuXdrUTikGfFBhTimK1O4/kGV9SOGzJguajVZaPIOU4WmGOuALpCEFHQoIz1R+N7ZFqk1L3cvdtfxxtfIBGleXl91CKm8BdAXcNVonhwFDodRQWr4QUWqRig==",
    "mobile_phone": "eQa4SIQ2XJW68Kya4AFg5RNrLvwZf9hJCBerx99LZL0KxBjqZb1nP0l8JtWe8mzSJZgYM9i7qRWdhbtzXm8I5fxU8bCmBZX0ODyy6FAKPSacDtfQLLHpGW5Q/j07gimx5hq5n4x/vLbr3i3yKTOm1lbCeiDOOltDxAhnRoHI6pu61BBNwrD7Y8k9CKwTWCccRcGLJBnD9Wj/RYu2c2MFGMZitw/kCJk4fyuSzTC6vMMb2qpCMvWljgTn3LgCe4YX6ukJm2vf4C684XzsKL8qCzgMM4lj7QqTEVakU7uqonAuPnu4G4mzhlmcBiG4U80FILrv0UYjmuV9FxlJWVj5iQ=="
  },
  "need_account_info": false,
  "sales_scene_info": {
    "store_name": "测试店铺信息",
    "store_url": "http://test.xxx.com/test.php"
  },
  "merchant_shortname": "大红料",
  "out_request_no": "20210721171352"
}
```

格式化后你的参数，直觉是`id_card_valid_time` 这个参数格式有问题，这里[官方文档](https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter7_1_1.shtml)要求是`string`，示例代码给了俩值`2026-06-06，长期`，示例`JSON`是单值`"2026-06-06"`，这块我没接入过，不过按经验整理过的文档可以翻[这里](https://thenorthmemory.github.io/wechatpay-openapi/#/%E5%95%86%E6%88%B7%E8%BF%9B%E4%BB%B6%E2%88%99%E7%89%B9%E7%BA%A6%E5%95%86%E6%88%B7%E8%BF%9B%E4%BB%B6/post_v3_applyment4sub_applyment_)，完整JSON可能如下：

```json
{
  "business_code": "string",
  "contact_info": {
    "contact_name": "string",
    "contact_id_number": "string",
    "openid": "string",
    "mobile_phone": "string",
    "contact_email": "user@example.com"
  },
  "subject_info": {
    "subject_type": "SUBJECT_TYPE_INDIVIDUAL",
    "business_license_info": {
      "license_copy": "string",
      "license_number": "string",
      "merchant_name": "string",
      "legal_person": "string"
    },
    "certificate_info": {
      "cert_copy": "string",
      "cert_type": "CERTIFICATE_TYPE_2388",
      "cert_number": "string",
      "merchant_name": "string",
      "company_address": "string",
      "legal_person": "string",
      "period_begin": "2021-07-22",
      "period_end": "string"
    },
    "organization_info": {
      "organization_copy": "string",
      "organization_code": "string",
      "org_period_begin": "2021-07-22",
      "org_period_end": "string"
    },
    "certificate_letter_copy": "string",
    "identity_info": {
      "id_doc_type": "IDENTIFICATION_TYPE_IDCARD",
      "id_card_info": {
        "id_card_copy": "string",
        "id_card_national": "string",
        "id_card_name": "string",
        "id_card_number": "string",
        "card_period_begin": "2021-07-22",
        "card_period_end": "string"
      },
      "id_doc_info": {
        "id_doc_copy": "string",
        "id_doc_name": "string",
        "id_doc_number": "string",
        "doc_period_begin": "2021-07-22",
        "doc_period_end": "string"
      },
      "owner": true
    },
    "ubo_info": {
      "id_type": "IDENTIFICATION_TYPE_IDCARD",
      "id_card_copy": "string",
      "id_card_national": "string",
      "id_doc_copy": "string",
      "name": "string",
      "id_number": "string",
      "id_period_begin": "2021-07-22",
      "id_period_end": "string"
    }
  },
  "business_info": {
    "merchant_shortname": "string",
    "service_phone": "string",
    "sales_info": {
      "sales_scenes_type": [
        "SALES_SCENES_STORE"
      ],
      "biz_store_info": {
        "biz_store_name": "string",
        "biz_address_code": "string",
        "biz_store_address": "string",
        "store_entrance_pic": [
          "string"
        ],
        "indoor_pic": [
          "string"
        ],
        "biz_sub_appid": "string"
      },
      "mp_info": {
        "mp_appid": "string",
        "mp_sub_appid": "string",
        "mp_pics": [
          "string"
        ]
      },
      "mini_program_info": {
        "mini_program_appid": "string",
        "mini_program_sub_appid": "string",
        "mini_program_pics": [
          "string"
        ]
      },
      "app_info": {
        "app_appid": "string",
        "app_sub_appid": "string",
        "app_pics": [
          "string"
        ]
      },
      "web_info": {
        "domain": "string",
        "web_authorisation": "string",
        "web_appid": "string"
      },
      "wework_info": {
        "sub_corp_id": "string",
        "wework_pics": [
          "string"
        ]
      }
    }
  },
  "settlement_info": {
    "settlement_id": "string",
    "qualification_type": "string",
    "qualifications": [
      "string"
    ],
    "activities_id": "string",
    "activities_rate": "string",
    "activities_additions": [
      "string"
    ]
  },
  "bank_account_info": {
    "bank_account_type": "BANK_ACCOUNT_TYPE_CORPORATE",
    "account_name": "string",
    "account_bank": "工商银行",
    "bank_name": "施秉县农村信用合作联社城关信用社",
    "bank_branch_id": "402713354941",
    "account_number": "ciphertext"
  },
  "addition_info": {
    "legal_person_commitment": "string",
    "legal_person_video": "string",
    "business_addition_pics": [
      "string"
    ],
    "business_addition_msg": "string"
  }
}
```

如果发现官方文档描述的不对，欢迎去在线技术支持，同时如果有对接成功，也欢迎把更定后的数据结构，提个PR至 https://github.com/TheNorthMemory/wechatpay-openapi 这里

**Comment by sentangle** [comment]
### 可以了，多谢大佬及时反馈，自己调试后发现自己代码写有问题
![image](https://user-images.githubusercontent.com/6250675/126581982-7163aae9-1746-4968-b899-4ae5988e16af.png)

### 返回正确信息
![image](https://user-images.githubusercontent.com/6250675/126582004-173b1f71-9909-4da9-bae1-373fd17264b7.png)
