### ISSUE TITLE
创建支付分订单API 报错，乱码

### ISSUE THREAD

**Issue by ruoshuiyx** [wechatpay-apiv3/wechatpay-php#21]
Client error: `POST https://api.mch.weixin.qq.com/v3/payscore/serviceorder` resulted in a `400 Bad Request` response:
    {"code":"PARAM_ERROR","message":"µ£ìÕèíÕ╝ÇÕºïµùÂÚù┤õ©ìÞâ¢µù®õ║ÄÞ░âþö¿µÄÑÕÅúµùÂÚù┤´╝îµêûõ╝áÕàÑÕø║Õ«ÜÕÇ╝OnAcceptÞí¿þñ║þö¿µ (truncated...)

请问这个是什么原因

**Comment by TheNorthMemory** [comment]
建议阅读 [PHP字符编码的要求](https://www.php.net/manual/zh/mbstring.php4.req.php)，PHP的特性之一就是，所执行的PHP文件如果是GBK/CP936/ISO-8869-1等编码，那参数就自动继承此编码；而微信支付接口，是仅支持UTF-8编码，建议你调整下PHP文件编码为utf-8格式再试试。
