### ISSUE TITLE
下载器生成平台证书-失败，错误原因：调用了未定义的方法

### ISSUE THREAD

**Issue by zhoufei666** [wechatpay-apiv3/wechatpay-php#22]
![image](https://user-images.githubusercontent.com/20034765/128165356-9b58b74a-6d30-4f3e-9946-c6ea246ae7f8.png)

**Comment by zhoufei666** [comment]
当 使用了错误的 -k参数 时，这种情况会出现

**Comment by TheNorthMemory** [comment]
这里是有点问题，`-k` apiv3Key参数如果没给对，异常从`AesGcm::decrypt` 抛出了，健壮性有待修复；请给对apiv3Key值，可正常下载`平台证书`。
