### ISSUE TITLE
array_key_exists($config['serial'], $config['certs'])  ， 这里是应该取非吗，我检查了所有配置

### ISSUE THREAD

**Issue by BigTreeGo** [wechatpay-apiv3/wechatpay-php#26]
![image](https://user-images.githubusercontent.com/30651682/129343862-e9808e84-bf5b-443e-89ca-d748edefd421.png)

**Comment by TheNorthMemory** [comment]
不是取非，是你不恰当地把**商户证书序列号**，填在了**平台证书序列号**位置，SDK替你做了判断，你这种配置方法错了。

举个例子，都是**钥匙**，你家的**钥匙**和我家的**钥匙**，都是钥匙，但是你不能拿你家的来开我家的门，这就是**非对称**加解密技术的概要。

```php
// 平台证书，可由下载器 `./bin/CertificateDownloader.php` 生成并假定保存为 `/path/to/wechatpay/cert.pem`
$platformCertificateFilePath = '/path/to/wechatpay/cert.pem';
// 加载平台证书
$platformCertificateInstance = PemUtil::loadCertificate($platformCertificateFilePath);
// 解析平台证书序列号
$platformCertificateSerial = PemUtil::parseCertificateSerialNo($platformCertificateInstance);
```

- `certs[$serial_number => #resource]` 为通过下载工具下载的平台证书`key/value`键值对，键为`平台证书序列号`，值为`平台证书`pem格式的纯字符串或者文件`resource`格式

另：你检查逻辑唯独缺了README注释说明，README要耐心读一下。

**Comment by BigTreeGo** [comment]
谢谢啦 我理解错了证书序列号
