### ISSUE TITLE
请问现在api 怎么替换 handle  我如果想兼容于协助框架

### ISSUE THREAD

**Issue by joker02161** [wechatpay-apiv3/wechatpay-php#28]

**Comment by TheNorthMemory** [comment]
初始化入参上，可以加入

```php
Builder::factory(['handler' => $stack]);
```

这个`$stack`要求是 `\Guzzle\HandlerStack`的一个实例，因为SDK中间件是在这个上面注册的，其他的不支持。

例如测试用例上，就是这么做的：

https://github.com/wechatpay-apiv3/wechatpay-php/blob/8de171a22413dbdfc76f12fab85c692de5d3b1bd/tests/ClientDecoratorTest.php#L136-L141

https://github.com/wechatpay-apiv3/wechatpay-php/blob/8de171a22413dbdfc76f12fab85c692de5d3b1bd/tests/ClientDecoratorTest.php#L335-L341

**Comment by joker02161** [comment]
好的 感谢 我这边实现下
