### ISSUE TITLE
服务商相关 factory 构建 instance

### ISSUE THREAD

**Issue by joker02161** [wechatpay-apiv3/wechatpay-php#31]
请问 服务商也是这样么 [‘mchid’=>服务商sp_mchid, ‘serial ’=> 服务商证书序列号, ‘privatKey ’=>服务商私钥,certs[平台证书序列号=> #平台证书内容] ] 这样么

**Comment by TheNorthMemory** [comment]
对的，服务商配置跟普通商户是一样初始化方法，即：

```php
$instance = Builder::factory([
    'mchid'      => '服务商sp_mchid',
    'serial'     => '服务商证书序列号',
    'privateKey' =>'服务商私钥',
    'certs'      => [
        '平台证书序列号' => '#平台证书内容',
    ],
]);
```

**Comment by joker02161** [comment]
好的 明白了 请求参数 的话 怎么传呢 能提供个例子吗？

**Comment by TheNorthMemory** [comment]
例如：

```php
$res = $instance
->v3->ecommerce->refunds->outRefundNo->{'{out_refund_no}'}
->getAsync([
    'query'         => ['sub_mchid' => '子商户号'],
    'out_refund_no' => '商户订单号',
])
->then(static function(){})
->wait();
```

**Comment by joker02161** [comment]
好的明白了 传入过的参数需要在传入吗？ 例如 [
    'mchid'      => '服务商sp_mchid',
] 这些？

**Comment by TheNorthMemory** [comment]
> 好的明白了 传入过的参数需要在传入吗？ 例如 [
> 'mchid' => '服务商sp_mchid',
> ] 这些？

如果[文档中心](https://pay.weixin.qq.com/wiki/doc/apiv3_partner/index.shtml)上，参数描述有 `'mchid': '服务商sp_mchid'`，则请求参数就需要，没有描述就不需要。

**Comment by joker02161** [comment]
好的 非常感谢
