### ISSUE TITLE
New features are all in `APIv3`, there's no reason to continue use this kind client since v2.0.

### ISSUE THREAD

**Issue by suiaiyun** [wechatpay-apiv3/wechatpay-php#38]
这条该死的提示为什么一直关不掉？display_errors = Off 也不行？

**Comment by TheNorthMemory** [comment]
https://github.com/wechatpay-apiv3/wechatpay-php/blob/b7398ef769e81e8cf79a39842cd53413733f0f0b/tests/OpenAPI/V2MmpaymkttransfersPromotionTransfersTest.php#L111-L118

参考上述测试用例覆盖，用 `@$endpoint->postAsync` 可屏蔽掉提示。。。

**Comment by suiaiyun** [comment]
谢谢，按照您的方法已解决，nice
