### ISSUE TITLE
企业付款到零钱API什么时候发布V3版本

### ISSUE THREAD

**Issue by terryops** [wechatpay-apiv3/wechatpay-php#39]
我们经常需要用这个API，想等V3出了再迁移到这个sdk。
因为你们说「本SDK将在v2.0版移除对APIv2的默认支持」，到时候我们还会增加工作量。

**Comment by TheNorthMemory** [comment]
除非官方完全放弃APIv2接口。。。本SDK的**v2.0**目前还没有计划，也可能“永远”也抵达不了。。。
