### ISSUE TITLE
现金红包V2接口证书提示错误

### ISSUE THREAD

**Issue by suiaiyun** [wechatpay-apiv3/wechatpay-php#40]
证书在v3接口使用正常，在v2的现金红包接口错误码：CA_ERROR，证书出错，请登录微信支付商户平台下载证书
请问证书有效期没有失效，为什么会提示这个错误？应该怎样解决？

**Comment by TheNorthMemory** [comment]
提供一下你的APIv2的初始化代码

**Comment by suiaiyun** [comment]
初始化代码：
$this->instance = Builder::factory([
            'mchid' => $this->mchid,
            'serial' => $this->serial,
            'privateKey' => PemUtil::loadPrivateKey(Env::get('wxpay.privatekey', '')),
            // 平台证书
            'certs' => [
                // 证书序列号 => 证书文件
                PemUtil::parseCertificateSerialNo($wxPayCertificate) => $wxPayCertificate
            ],
            // APIV2 -- 不使用APIv2可选
            'secret' => Env::get('wxpay.apiv2key', ''),
            'merchant' => [
                // 商户证书文件路径
                'cert' => Env::get('wxpay.merchantcert', ''),
                // 商户API私钥文件路径
                'key' => Env::get('wxpay.privatekey', ''),
            ],
        ]);

.env配置文件：
[wxpay]
mchid=xxxxx
appid=wx0000000000
serial=AAAABBBBCCCCC
apiv3key=DDDDSSsadasd
privatekey=/vshare/cert/apiclient_key.pem
merchantcert=/vshare/cert/apiclient_cert.pem
apiv2key=xxxxxxx

**Comment by TheNorthMemory** [comment]
官方文档地址是： https://pay.weixin.qq.com/wiki/doc/api/tools/cash_coupon.php?chapter=13_4&index=3

你请求代码，是不是如下？尤其 `security` 有没有给呢？

```php
$instance->v2->mmpaymkttransfers->sendredpack->post(['xml' => [
	'mch_billno' => '',
	'mch_id' => '',
	'wxappid' => '',
	'send_name' => '',
	're_openid' => '',
	'total_amount' => '',
	'total_num' => '',
	'wishing' => '',
	'client_ip' => '',
	'act_name' => '',
	'remark' => '',
	'scene_id' => '',
	'nonce_str' => '',
	'risk_info' => '',
],
'security' => true //请求需要双向证书
]);
```

**Comment by suiaiyun** [comment]
security 这个没有给，需要加上吗？我现在加上试一下

**Comment by TheNorthMemory** [comment]
文档上写着， **是否需要证书 | 是（证书及使用说明详见商户证书）**，这个要在请求的时候，特别添加** security** 参数，才会被加载上，默认不加载的。

**Comment by suiaiyun** [comment]
加上后不提示证书错误了，提示签名错误，我再排查一下，谢谢您啦

**Comment by TheNorthMemory** [comment]
文档上写着， **是否需要证书 | 是（证书及使用说明详见商户证书）**，这个要在请求的时候，特别添加 **security** 参数，才会被加载上，默认不加载的。

README上写着。。。

`APIv2`末尾驱动的 `HTTP METHOD(POST)` 方法入参 `array $options`，可接受类库定义的两个参数，释义如下：

- `$options['nonceless']` - 标量 `scalar` 任意值，语义上即，本次请求不用自动添加`nonce_str`参数，推荐 `boolean(True)`
- `$options['security']` - 布尔量`True`，语义上即，本次请求需要加载ssl证书，对应的是初始化 `array $config['merchant']` 结构体

**Comment by suiaiyun** [comment]
额。。。没仔细看文档，草率啦，嘿嘿。。。谢谢您了
