### ISSUE TITLE
apiv2接口SIGN_ERROR错误

### ISSUE THREAD

**Issue by suiaiyun** [wechatpay-apiv3/wechatpay-php#41]
请求前的参数：
Array
(
    [xml] => Array
        (
            [mch_billno] => etGkDmT3BJyuhnhU9d
            [mch_id] => xxxxx
            [wxappid] => wx01111111
            [send_name] => aaaaa
            [re_openid] => o8xSOxxxxxxx
            [total_amount] => 100
            [total_num] => 1
            [wishing] => 红包祝福语
            [client_ip] => 192.168.0.1
            [act_name] => 活动名称
            [remark] => 备注
        )
    [security] => 1
)

apiv2密钥尝试更换过，更换后还是返回签名错误，请问我要怎样处理？
请求代码：$instance->v2->mmpaymkttransfers->sendredpack->postAsync($data)

**Comment by TheNorthMemory** [comment]
稍等，这里应该有点问题，在看。

**Comment by suiaiyun** [comment]
怎样了？有解决方案了吗？

**Comment by TheNorthMemory** [comment]
这是个`bug`，`Formatter::ksort`在排序时，是按照键值按**自然序**排的，`re_` 跟 `rem` 在自然序列下， `rem`排在`re_`之前；而官方文档要求是**字典序**，字符串第3位的 `_` chrcode是95， `m`是105，字典序排的话，`re_`应该排在`rem`之前。

已找到问题所在点，在写测试用例覆盖中。。。

**Comment by suiaiyun** [comment]
好的，那我等待更新新版本了
