### ISSUE TITLE
当金额为1.1元时，jsapi下单报错

### ISSUE THREAD

**Issue by youngda** [wechatpay-apiv3/wechatpay-php#43]
这个接口` $resp = $instance->chain('v3/pay/transactions/jsapi')->post(['json' => [ ], ]);`

Client error: `POST https://api.mch.weixin.qq.com/v3/pay/transactions/jsapi` resulted in a `400 Bad Request` response:
{"code":"PARAM_ERROR","detail":{"location":"body","value":110.00000000000001},"message":"无法将 JSON 输入源“/bod (truncated...)

**Comment by TheNorthMemory** [comment]
这个是入参数`amount`类型不正确所致，数学运算如 `1.1*100` 返回值是`float`浮点型，文档要求是`int`整型，复现如下：

```php
php > var_dump(1.1*100);
float(110)

php > var_dump((int)1.1*100);
int(100)

php > var_dump(intval(1.1*100));
int(110)
```

```php
php > var_dump(json_encode(['amount' => 1.1*100]));
string(29) "{"amount":110.00000000000001}"
```

建议对金额做类型转换，可类似如下任意一种：

```php
php > var_dump(json_encode(['amount' => (int)1.1*100]));
string(14) "{"amount":100}"

php > var_dump(json_encode(['amount' => intval(1.1*100)]));
string(14) "{"amount":110}"
```

另外要注意PHP官方文档上的警告⚠️[永远不要相信浮点数结果精确到了最后一位，也永远不要比较两个浮点数是否相等](https://www.php.net/manual/zh/language.types.float.php)

**Comment by youngda** [comment]
谢谢
