### ISSUE TITLE
证书下载错误

### ISSUE THREAD

**Issue by XuanDeMeng** [wechatpay-apiv3/wechatpay-php#44]
*   Trying 14.215.140.116...
* TCP_NODELAY set
* Expire in 74995 ms for 3 (transfer 0x1ff75985080)
* Expire in 200 ms for 4 (transfer 0x1ff75985080)
* Connected to api.mch.weixin.qq.com (14.215.140.116) port 443 (#0)
* ALPN, offering http/1.1
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
cURL error 60:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.mch.weixin.qq.com/v3/certificates
#0 D:\phpstudy_pro\WWW\video_project\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle
), Array)
#1 D:\phpstudy_pro\WWW\video_project\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandl
er), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 D:\phpstudy_pro\WWW\video_project\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(236): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandl
er), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 D:\phpstudy_pro\WWW\video_project\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(168): GuzzleHttp\Handler\CurlMultiHandler->processMessages()
#4 D:\phpstudy_pro\WWW\video_project\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(183): GuzzleHttp\Handler\CurlMultiHandler->tick()
#5 D:\phpstudy_pro\WWW\video_project\vendor\guzzlehttp\promises\src\Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#6 D:\phpstudy_pro\WWW\video_project\vendor\guzzlehttp\promises\src\Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#7 D:\phpstudy_pro\WWW\video_project\vendor\guzzlehttp\promises\src\Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#8 D:\phpstudy_pro\WWW\video_project\vendor\guzzlehttp\promises\src\Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#9 D:\phpstudy_pro\WWW\video_project\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#10 D:\phpstudy_pro\WWW\video_project\vendor\wechatpay\wechatpay\bin\CertificateDownloader.php(109): GuzzleHttp\Promise\Promise->wait()
#11 D:\phpstudy_pro\WWW\video_project\vendor\wechatpay\wechatpay\bin\CertificateDownloader.php(47): CertificateDownloader->job(Array)
#12 D:\phpstudy_pro\WWW\video_project\vendor\wechatpay\wechatpay\bin\CertificateDownloader.php(235): CertificateDownloader->run()
#13 {main}

**Comment by TheNorthMemory** [comment]
```
SSL certificate problem: unable to get local issuer certificate
cURL error 60: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) 
```

你本地的Windows环境，不支持当前CA bundle证书

```
* Server certificate:
*  subject: C=CN; ST=Guangdong Province; L=Shenzhen; O=Shenzhen Tencent Computer Systems Company Limited; CN=payapp.weixin.qq.com
*  start date: Jan  5 00:00:00 2021 GMT
*  expire date: Feb  4 23:59:59 2022 GMT
*  subjectAltName: host "api.mch.weixin.qq.com" matched cert's "api.mch.weixin.qq.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert Secure Site CN CA G3
*  SSL certificate verify ok.
> GET /v3/certificates HTTP/1.1
```

你需要设置/更新一下你本地windows环境的ca证书，看 https://curl.haxx.se/libcurl/c/libcurl-errors.html 这个链接里的提示

**Comment by TheNorthMemory** [comment]
## 解决办法

去如下网址下载最新证书，然后放置php.ini的指定目录里面

[证书网址](https://curl.haxx.se/ca/cacert.pem)

修改 php.ini，phpstudy，v8.0的版本

```
curl.cainfo = "D:\phpstudy_pro\Extensions\php\php7.3.4nts\extras\ssl\cacert.pem"
```

然后访问就正常了
————————————————
版权声明：本文为CSDN博主「hxthon」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/u013866352/article/details/105413790/

**Comment by XuanDeMeng** [comment]
嗯。按照你的操作了，但 报错依旧啊，请问下，这次是报的什么意思呢？







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wechatpay-apiv3/wechatpay-php"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月11日(星期六) 下午3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wechatpay-apiv3/wechatpay-php] 证书下载错误 (#44)





 
解决办法
 
去如下网址下载最新证书，然后放置php.ini的指定目录里面
 
证书网址
 
修改 php.ini，phpstudy，v8.0的版本
 curl.cainfo = "D:\phpstudy_pro\Extensions\php\php7.3.4nts\extras\ssl\cacert.pem"  
然后访问就正常了
 ————————————————
 版权声明：本文为CSDN博主「hxthon」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
 原文链接：https://blog.csdn.net/u013866352/article/details/105413790/
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TheNorthMemory** [comment]
> 嗯。按照你的操作了，但 报错依旧啊，请问下，这次是报的什么意思呢？ * Trying 14.215.140.116... * TCP_NODELAY set * Expire in 74995 ms for 3 (transfer 0x27b737a27b0) * Expire in 200 ms for 4 (transfer 0x27b737a27b0) * Connected to api.mch.weixin.qq.com (14.215.140.116) port 443 (#0) * ALPN, offering http/1.1 * SSL certificate problem: unable to get local issuer certificate * Closing connection 0 cURL error 60: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api #0 D:\phpstudy_pro\WWW\video_project\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.ph ), Array) #1 D:\phpstudy_pro\WWW\video_project\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.ph er), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 D:\phpstudy_pro\WWW\video_project\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandl er), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))

一样的问题，还是加载不上正确的 `ca bundle` 文件

**Comment by XuanDeMeng** [comment]
Script CertificateDownloader.php handling the __exec_command event returned with error code 255 

额，现在又报这个了

**Comment by XuanDeMeng** [comment]
好了。好了。搞定了。！哎，一波三折啊。搞了3天了！！

**Comment by TheNorthMemory** [comment]
> Script CertificateDownloader.php handling the __exec_command event returned with error code 255
> 
> 额，现在又报这个了

这个问题可能跟 https://github.com/Codeception/Codeception/issues/3662#issuecomment-257416816 这个有关，你的`php.ini`的 error_reporting 错误级别，建议调整成 `E_STRICT | E_DEPRECATED`
