### ISSUE TITLE
注释太洋气了

### ISSUE THREAD

**Issue by bdHeart** [wechatpay-apiv3/wechatpay-php#46]
考虑一下中文注释吧

**Comment by TheNorthMemory** [comment]
依赖包，大部分都是`英文`的，文档咱就用中文吧

**Comment by xy-peng** [comment]
@bdHeart 你有什么好的更具体的建议吗？面向使用者的角度考虑，对外暴露的接口中生成文档或者ide智能提示的注释，使用中文？

**Comment by bdHeart** [comment]
> @bdHeart 你有什么好的更具体的建议吗？面向使用者的角度考虑，public接口中生成文档或者ide智能提示的注释，使用中文？

所有写给阅读者的都应该是中文，这是最理想的

**Comment by anlondon** [comment]
赞同楼上，毕竟微信国人用得更多

**Comment by CJayHe** [comment]
中国的软件为啥不优先使用中文注释
