### ISSUE TITLE
付款到零钱，走的otherwise，返回空，无法确认交易结果

### ISSUE THREAD

**Issue by zhoufei666** [wechatpay-apiv3/wechatpay-php#47]
问题：
1.交易能成功：收到转账、商户后台也能看见交易信息，但是接口直接走了otherwise且返回了空数组，导致无法确认交易结果
2.交易查询，同样走了otherwise，拿不到交易结果
3.此问题已同技术客服确认
![image](https://user-images.githubusercontent.com/20034765/133718386-ad6edc6c-ad55-410f-ac16-253ec21ae4c3.png)

代码信息：
1.调用sdk
![image](https://user-images.githubusercontent.com/20034765/133717981-478a47b1-872a-4dca-95ce-5b56fda060af.png)
2.输出结果
![image](https://user-images.githubusercontent.com/20034765/133718015-173750d7-6ee2-42a9-a70c-ed3559ce5ba5.png)

**Comment by TheNorthMemory** [comment]
https://github.com/wechatpay-apiv3/wechatpay-php/blob/e2982e994d644cfcc9f887d2f19d5f8b36a43fc0/tests/OpenAPI/V2MmpaymkttransfersPromotionTransfersTest.php#L129-L135

参考这个测试用例，把 `     $txt = (string) $res->getBody(); ` 打印出来看看是个啥？

**Comment by TheNorthMemory** [comment]
示例`README.md`问题，`v2`的otherwise入参 `$e` 就是 `\GuzzeHttp\Psr7\Response`， 你截图里的

```php
->otherwise(static function($e) {
    if ($e instanceof \GuzzleHttp\Promise\RejectionException) {
        return Transformer::toArray((string)$e->getReason()->getBody());
    }
    return [];
})
```

走不进去 if ($e instanceof) 语句内，就直接 返回到了 `return [];`，

建议如下调整代码：

```php
->otherwise(static function($e) {
    if ($e instanceof \GuzzleHttp\Promise\RejectionException) {
        return Transformer::toArray((string)$e->getReason()->getBody());
    }
    if ($e instanceof \Psr\Http\Message\MessageInterface) {
        return Transformer::toArray((string)$e->getBody());
    }
    return [];
})
```

**Comment by TheNorthMemory** [comment]
一般`otherwise`逻辑是处理异常的，异常的种类会非常多，比如没有给客户端证书，入参就是`ConnectException`异常类，也建议做类型推断判断处理。

不过，针对官方这个特殊接口(返回无`sign`字典），正确处理应该是在请求入参上，添加上 `handler` 入参，声明特殊`HandlerStack`即返回值无须验签，这样可以走正常的`then`逻辑，代码示例如下：

```php
$stack = $instance->getDriver()->select(ClientDecoratorInterface::XML_BASED)->getConfig('handler');
/** @var HandlerStack $stack */
$stack->remove('transform_response');

$instance->v2->mmpaymkttransfers->promotion->transfers->postAsync([
    'security' => true,
    'handler' => $stack,
    'xml' => [
    // ...
    ],
])->then()->wait();
```

**Comment by zhoufei666** [comment]
> 示例`README.md`问题，`v2`的otherwise入参 `$e` 就是 `\GuzzeHttp\Psr7\Response`， 你截图里的
> 
> ```
> ->otherwise(static function($e) {
>     if ($e instanceof \GuzzleHttp\Promise\RejectionException) {
>         return Transformer::toArray((string)$e->getReason()->getBody());
>     }
>     return [];
> })
> ```
> 
> 走不进去 if ($e instanceof) 语句内，就直接 返回到了 `return [];`，
> 
> 建议如下调整代码：
> 
> ```
> ->otherwise(static function($e) {
>     if ($e instanceof \GuzzleHttp\Promise\RejectionException) {
>         return Transformer::toArray((string)$e->getReason()->getBody());
>     }
>     if ($e instanceof \Psr\Http\Message\MessageInterface) {
>         return Transformer::toArray((string)$e->getBody());
>     }
>     return [];
> })
> ```
大佬的 此方法同样适用于 【转账到零钱 - 查询付款】

**Comment by leoxiaoping** [comment]
> ```
> if ($e instanceof \Psr\Http\Message\MessageInterface) {
>         return Transformer::toArray((string)$e->getBody());
>     }
> ```
改下readme.md 吧
