### ISSUE TITLE
APIv3回调通知 样例代码 中的错误?

### ISSUE THREAD

**Issue by simon-tu-ke** [wechatpay-apiv3/wechatpay-php#48]
```
if ($timeOffsetStatus && $verifiedStatus) {
    // 这个变量用来干什么的?
    $inBodyArray = (array)json_decode($inBody, true);
    // 这段代码是什么情况????
    ['resource' => [
        'ciphertext'      => $ciphertext,
        'nonce'           => $nonce,
        'associated_data' => $aad
    ]] = $inBodyArray;
    $inBodyResource = AesGcm::decrypt($ciphertext, $apiv3Key, $nonce, $aad);
    $inBodyResourceArray = (array)json_decode($inBodyResource, true);
    // print_r($inBodyResourceArray);// 打印解密后的结果
}
```

**Comment by TheNorthMemory** [comment]
## APIv3回调通知
1. 从请求头部Headers，拿到Wechatpay-Signature、Wechatpay-Nonce、Wechatpay-Timestamp、Wechatpay-Serial及Request-ID，商户侧Web解决方案可能有差异，请求头可能大小写不敏感，请根据自身应用来定；
2. 获取请求body体的JSON纯文本；
3. 检查通知消息头标记的Wechatpay-Timestamp偏移量是否在5分钟之内；
4. 调用SDK内置方法，构造验签名串然后经Rsa::verfify验签；
5. 消息体需要解密的，调用SDK内置方法解密；

> ```php
> if ($timeOffsetStatus && $verifiedStatus) {
>     // 这个变量用来干什么的?
>>  // **对获取的json进行格式转换，从json文本转换成php array**
>     $inBodyArray = (array)json_decode($inBody, true);
>     // 这段代码是什么情况????
>>  // **通知消息是加密的，需要调用AesGcm函数解密**
>     ['resource' => [
>         'ciphertext'      => $ciphertext,
>         'nonce'           => $nonce,
>         'associated_data' => $aad
>     ]] = $inBodyArray;
>     $inBodyResource = AesGcm::decrypt($ciphertext, $apiv3Key, $nonce, $aad);
>     $inBodyResourceArray = (array)json_decode($inBodyResource, true);
>     // print_r($inBodyResourceArray);// 打印解密后的结果
> }
> ```
