### ISSUE TITLE
v2 企业付款到零钱 报错

### ISSUE THREAD

**Issue by lindaoling** [wechatpay-apiv3/wechatpay-php#50]
按README里面例子使用 业付款到零钱接口，报错以下错误

`Argument 2 passed to WeChatPay\\Transformer::content() must be of the type string, integer given, called in xxx\vendor\\wechatpay\\wechatpay\\src\\Transformer.php on line 156"`

**Comment by TheNorthMemory** [comment]
文档上`有误`，按照XML规范，所有内容均是文本，即使接口描述是`int`也需要转换成文本，即：

```php
      'amount' => (string) 10099,
```
