### ISSUE TITLE
请问一下，为什么提示串号不允许呢？我完全是按照商户证书的生成流程制作的啊

### ISSUE THREAD

**Issue by hqaht** [wechatpay-apiv3/wechatpay-php#53]
WeChatPay\Exception\InvalidArgumentException: The `certs(xxxxxxxxx)` contains the merchant's certificate serial number(xxxxxxxx) which is not allowed here. in file /www/wwwroot/xxx/vendor/wechatpay/wechatpay/src/ClientJsonTrait.php on line 190

**Comment by TheNorthMemory** [comment]
在非对称加密技术领域，**公钥** （商户证书）是给对方的，自己基本不用；这里强校验商户证书及序列号，就是为了避免配错**平台证书公钥**而为。

**Comment by simosun** [comment]
老师，也出现这个问题，这个商户API证书序列号变量的值，应该怎么处理？

**Comment by simosun** [comment]
我从管理后台，证书哪里，复制的值，还是上面一样的错；
