### ISSUE TITLE
使用API V3协议，当segment中，`uri_template`动态参数中有大写英文字母会被转换成小写英文字母

### ISSUE THREAD

**Issue by jodumadie** [wechatpay-apiv3/wechatpay-php#56]
使用API V3协议，当segment中，`uri_template`动态参数中有大写英文字母会被转换成小写英文字母。

**Comment by TheNorthMemory** [comment]
是的，类库中的`segment`是大小写敏感的，含义如下：

- 首字符大写，用于标记为`interface`；
- 中间字符大写，用于还原连字符hyphen(`-`)；
- 首尾字符是下划线understore(`_`)，用于还原`uri_template`字面量字符串；
- 特殊语法关键字，如`return`, `/`, `use` 需要用到 `uri_template` 构造；

特殊`URI`规则总结于 https://github.com/TheNorthMemory/wechatpay-openapi 项目`README`所列如下：

| 源URI | 模版变量 | 值 |
| --- | --- | --- |
| `secapi/mch/addInstitutionsub` | `{addinstitutionsub}` [^1] | `addInstitutionsub` |
| `secapi/mch/modifyInstitutionsub` | `{modifyinstitutionsub}` [^1] | `modifyInstitutionsub` |
| `secapi/mch/queryInstitutionsub` | `{queryinstitutionsub}` [^1] | `queryInstitutionsub` |
| `v3/applyment4sub/applyment/` | `{stub}` [^2] | |
| `v3/ecommerce/applyments/` | `{stub}` [^2] | |
| `v3/ecommerce/subsidies/return` | `{return}` [^3] | `return` |
| `v3/marketing/busifavor/coupons/return` | `{return}` [^3] | `return` |
| `v3/marketing/busifavor/coupons/use` | `{use}` [^4] | `use` |

[^1]: 源URI上含有`I`大写字符，需要用模版变量构造
[^2]: 源URI末尾以`/`结尾，需要值为用空的模版变量构造
[^3]: 源URI末尾segment单词是`return`，其为PHP语法关键字，需要用模版变量构造
[^4]: 源URI末尾segment单词是`use`，其为PHP语法关键字，需要用模版变量构造


建议 `uri_template` 保持与上述规则一致，即使用全小写及/或下划线形式`描述模版字面量`。

**Comment by yybawang** [comment]
### 有的接口的path里是有 openid 的，openid 是有大小写的了，转换后就得到一个乱掉的openid了，
我请求的支付服务商->发放优惠券接口
如图

![示例](https://raw.githubusercontent.com/yybawang/images/master/picgo20211203110728.png)

**Comment by TheNorthMemory** [comment]
@yybawang 有多种方式可以避免:

1. `->v3->marketing->favor->users->_openid_->coupons->post(['openid' => 'AbcdEF12345']);`
2.`->v3->marketing->favor->users->{'{openid}'}->coupons->post(['openid' => 'AbcdEF12345']);`
3. `->chain('{+myurl}'->post(['myurl' => 'v3/marketing/favor/users/AbcdEF12345/coupons']);`
4. `->{'{+myurl}'}->post(['myurl' => 'v3/marketing/favor/users/AbcdEF12345/coupons']);`

建议使用第一种方式，具有`IDE`提示.

**Comment by xy-peng** [comment]
看来需要增加一个常见问题，或者在链式调用的地方再加以强调。
