### ISSUE TITLE
为什么不所有接口都升级v3?

### ISSUE THREAD

**Issue by anhao** [wechatpay-apiv3/wechatpay-php#58]
为什么不所有接口都升级v3? 使用的时候还要一会使用v3,一会使用v2 。 这个都不统一一下。

**Comment by xy-peng** [comment]
主要是业务方面的原因，比如有的业务在v3有了新的替代品，但是大部分商户还习惯使用v2。比如 v2 的企业付款到零钱，v3对应的是[批量转账到零钱产品](https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/transfer/chapter2_1.shtml)。

**Comment by TheNorthMemory** [comment]
本sdk已经把apiv2/apiv3的差异消减到了最低，对接起来代码书写均是php原生`array`入参，不清楚你对哪部分内容还不清晰？
