### ISSUE TITLE
命令现在生成不了证书。php版本是7.3的。 环境是git shell

### ISSUE THREAD

**Issue by chriswenwu** [wechatpay-apiv3/wechatpay-php#59]
./bin/CertificateDownloader.php -k ${apiV3key} -m ${mchId} -f ${mchPrivateKeyFilePath} -s ${mchSerialNo} -o ${outputFilePath}

**Comment by xy-peng** [comment]
把失败的日志贴一下吧

**Comment by TheNorthMemory** [comment]
建议看下 [在PHP项目环境内，如何使用composer来下载平台证书](https://developers.weixin.qq.com/community/develop/article/doc/000ea8a607cfa81950ac2647e56c13) 教程

**Comment by chriswenwu** [comment]
已解决哈。。用了另外一个库。。 估计是什么东西没下导致的。
