### ISSUE TITLE
JSAPI下单 请求成功但是body为空

### ISSUE THREAD

**Issue by keke996** [wechatpay-apiv3/wechatpay-php#60]
> $instance->v3->pay
                ->transactions->jsapi->post(
                    ['json'=>[
                        'appid'=>$app_id,
                        'mchid'=>$mchid,
                        'description'=>$order_name,
                        'out_trade_no'=>$out_trade_no,
                        'notify_url'=>'test.com',
                        'amount'=>[
                            'total'=>(int) bcdiv( $order->good->price,100),
                        ],
                        'payer'=>[
                            'openid'=>$order->user->open_id,
                        ],
                    ]]
                )

（参数是正确的防止泄密像回调地址在这里是随便写的）
当我使用如上代码发起请求时，请求是通的，但是返回的body是空的这是为什么

**Comment by keke996** [comment]
Request-ID
08F0D0998C0610BF0518F0C1EEA30620DFF60E28FFE503-0

**Comment by keke996** [comment]
好吧，
$resp->getBody()->getContents()
这样才能拿到

**Comment by skrxf** [comment]
傻逼SDK，还要getContents()，害得我找半天
