### ISSUE TITLE
标题写错了

### ISSUE THREAD

**Issue by savingfor** [wechatpay-apiv3/wechatpay-php#62]
![image](https://user-images.githubusercontent.com/17944453/141047013-a0593751-f2e4-4407-b1aa-cfcf2ff9b175.png)
红色框起来的标题的应该是商户进件提交申请单API

**Comment by TheNorthMemory** [comment]
对，这个是 `进件` 接口，其中`敏感信息`如图示姓名/身份证号/电话/邮箱地址`要求需要RSA加密

**Comment by TheNorthMemory** [comment]
文档已调整并增加了说明
