### ISSUE TITLE
Cannot load privateKey from(/wechat/apiclient_key.pem).

### ISSUE THREAD

**Issue by nabeelzqadri** [wechatpay-apiv3/wechatpay-php#63]
i am trying to implement wechat pay into one of my client website.
Cannot load privateKey from(/wechat/apiclient_key.pem).

 but i am getting this error any suggestion

**Comment by TheNorthMemory** [comment]
How's your `factory()` codes? Could you attached those here?

**Comment by nabeelzqadri** [comment]
@TheNorthMemory here is my factor code.
`$instance = Builder::factory ([
                'mchid'       => $merchantId,
                'serial'      => $merchantCertificateSerial ,
                'privateKey'  => $merchantPrivateKeyInstance ,
                'certs'       => [
                    $platformCertificateSerial => $platformPublicKeyInstance ,
                ],
            ]);`

**Comment by TheNorthMemory** [comment]
Cannot load privateKey from(/wechat/apiclient_key.pem)

> This prompt was about the `$merchantPrivateKeyInstance`, maybe comes from the OS security policy. You may try to pass through the `PKEY`'s content like the following codes:
 ```php
$privateKeyContent =  file_get_content('/wechat/apiclient_key.pem');//maynot works both
$merchantPrivateKeyInstance = \WeChatPay\Crypto\Rsa::from($privateKeyContent);
```
> and then pass this veriables into `factory`  as the README/your codes did.

**Comment by nabeelzqadri** [comment]
> Cannot load privateKey from(/wechat/apiclient_key.pem)
> 
> > This prompt was about the `$merchantPrivateKeyInstance`, maybe comes from the OS security policy. You may try to pass through the `PKEY`'s content like the following codes:
> 
> ```
> $privateKeyContent =  file_get_content('/wechat/apiclient_key.pem');//maynot works both
> $merchantPrivateKeyInstance = \WeChatPay\Crypto\Rsa::from($privateKeyContent);
> ```
> 
> > and then pass this veriables into `factory`  as the README/your codes did.

thanks for your reply is this work for publicKey as well because now i am getting error on Public key @TheNorthMemory

**Comment by nabeelzqadri** [comment]
@TheNorthMemory is it possible to have `parseCertificateSerialNo` from content any help?

**Comment by TheNorthMemory** [comment]
> @TheNorthMemory is it possible to have `parseCertificateSerialNo` from content any help?

The public key is the platform's. It must be downloaded via the `/v3/certificates` OpenAPI. There's a cli command which is located in `bin/CertificateDownloader.php`.  Following the `bin/README.md` guides, you may get that.

And then it can be passed the file content as above into `parseCertificateSerialNo`.

**Comment by TheNorthMemory** [comment]
Additionally, the `cli` command shall be displayed the `platformCertificateSerial`, you may used it directly instead of `parseCertificateSerialNo` method. @nabeelzqadri

**Comment by TheNorthMemory** [comment]
@nabeelzqadri does there still a problem?

**Comment by nabeelzqadri** [comment]
No thanks for your in help...
