### ISSUE TITLE
商户API证书序列号

### ISSUE THREAD

**Issue by simosun** [wechatpay-apiv3/wechatpay-php#71]
WeChatPay\Exception\InvalidArgumentException: The certs(xxxxxxxxx) contains the merchant's certificate serial number(xxxxxxxx) which is not allowed here. in file /www/wwwroot/xxx/vendor/wechatpay/wechatpay/src/ClientJsonTrait.php on line 190
按照管理后台进行配置的，查询看见后台有一个关闭的issues里问过；怕老师看不见再一下；
请问商户API证书序列号要怎么配置？

**Comment by TheNorthMemory** [comment]
首先，证书序列号是唯一的；每个序列号对应一个公钥证书，**`非对称加解密`是需要互换`公钥`给对方的**；

官方没说的是:

- `商户公钥`是在`申请商户证书`那一刻就给到平台了；
- 而`平台公钥`是需要商户自己再从`接口下载`才能拿到；

SDK本身上需要依赖`平台公钥证书`去做返回值验签，这里做了强校验，就是为了避免拿`商户公钥`去验签，不合**`非对称加解密`规范**。

顾，这个提示，说明你漏了前置条件，即：通过API接口先行下载**平台公钥证书**。

**Comment by simosun** [comment]
感谢老师的解答，已经解决！
