### ISSUE TITLE
接口URL的变量后面还有路径名称

### ISSUE THREAD

**Issue by simosun** [wechatpay-apiv3/wechatpay-php#72]
老师，您好！
请问一下；
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter11_1_4.shtml
查询结算账户API
接口说明
适用对象：服务商 电商平台
请求URL：https://api.mch.weixin.qq.com/v3/apply4sub/sub_merchants/{sub_mchid}/settlement
请求方式：GET
这样的URL变量后面还有参数，pathname应该怎么处理？

**Comment by TheNorthMemory** [comment]
1. `->v3->apply4sub->sub_merchants->_sub_mchid_->setttlement->get(['sub_mchid' => '1234321']);`
2. `->chain('v3/apply4sub/sub_merchants/{sub_mchid}/settlement')->get(['sub_mchid' => '1234321']);`

**Comment by TheNorthMemory** [comment]
IDE 提示形如：

![image](https://user-images.githubusercontent.com/1631685/144979564-f6eafece-98d2-4c24-b9cf-5efac6f67f7b.png)

![image](https://user-images.githubusercontent.com/1631685/144979614-112e71a6-0617-4b33-b789-cdcd1ab47d13.png)

**Comment by simosun** [comment]
使用
1.->v3->apply4sub->sub_merchants->_sub_mchid_->setttlement->get(['sub_mchid' => '153321XXXX']);
返回：
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://api.mch.weixin.qq.com/v3/apply4sub/sub_merchants/153321XXXX/setttlement` resulted in a `404 Not Found` response in F:\UPUPW_AP7.2_64\htdocs\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

GuzzleHttp\Exception\ClientException: Client error: `GET https://api.mch.weixin.qq.com/v3/apply4sub/sub_merchants/153321XXXX/setttlement` resulted in a `404 Not Found` response in F:\UPUPW_AP7.2_64\htdocs\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

**Comment by TheNorthMemory** [comment]
> 使用 1.->v3->apply4sub->sub_merchants->_sub_mchid_->setttlement->get(['sub_mchid' => '153321XXXX']); 返回： Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://api.mch.weixin.qq.com/v3/apply4sub/sub_merchants/153321XXXX/setttlement` resulted in a `404 Not Found` response in F:\UPUPW_AP7.2_64\htdocs\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113
> 
> GuzzleHttp\Exception\ClientException: Client error: `GET https://api.mch.weixin.qq.com/v3/apply4sub/sub_merchants/153321XXXX/setttlement` resulted in a `404 Not Found` response in F:\UPUPW_AP7.2_64\htdocs\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

```setttlement``` 这个词儿手打误写多了个`t`了

**Comment by simosun** [comment]
哦，不好意思，我自己多打了t，谢谢老师
