### ISSUE TITLE
请问这个证书序列号怎么用？报错这个，都炸裂了，到底怎么用？？The `certs(202C9303CD55979093AEF51704C8059E0D0AFBC5)` contains the merchant's certificate serial number(202C9303CD55979093AEF51704C8059E0D0AFBC5) which is not allowed here.

### ISSUE THREAD

**Issue by melodyne** [wechatpay-apiv3/wechatpay-php#82]
The `certs(202C9303CD55979093AEF51704C8059E0D0AFBC5)` contains the merchant's certificate serial number(202C9303CD55979093AEF51704C8059E0D0AFBC5) which is not allowed here.

![image](https://user-images.githubusercontent.com/12462384/153718048-09b48122-bb1f-4d18-9dfc-e0d9d681204d.png)

**Comment by TheNorthMemory** [comment]
`README`上有写：

> ℹ️ 你需要先手工 `下载平台证书` 才能使用 SDK 发起请求。

相关见 #26

**Comment by melodyne** [comment]
好了 用错证书了

**Comment by melodyne** [comment]
3Q
