### ISSUE TITLE
建议SDK最低支持PHP7.0版本

### ISSUE THREAD

**Issue by aibow** [wechatpay-apiv3/wechatpay-php#86]
建议SDK最低支持PHP7.0版本。毕竟SDK要适配大众环境，而不是大众环境为了SDK升级已经部署的PHP环境。

**Comment by TheNorthMemory** [comment]
`PHP < 7.1` 可以使用 https://github.com/wechatpay-apiv3/wechatpay-guzzle-middleware , 本项目没计划支持PHP7.0，毕竟`PHP7.0`已经停止官方维护了 https://www.php.net/supported-versions.php

![image](https://user-images.githubusercontent.com/1631685/160312657-0643fc9c-f1ff-477c-b834-6508c561bc26.png)
