### ISSUE TITLE
有开发者反馈，其在部署应用时，腾讯云告警存在“木马文件”CertificateDownloader.php

### ISSUE THREAD

**Issue by TheNorthMemory** [wechatpay-apiv3/wechatpay-php#87]
<img width="327" alt="QQ20220418-214103@2x" src="https://user-images.githubusercontent.com/1631685/163816938-6a5c95d3-c856-48b0-a5db-700cd22969a1.png">
<img width="737" alt="QQ20220418-214000@2x" src="https://user-images.githubusercontent.com/1631685/163816946-129326e3-5602-40bc-bd43-972cc5e3eb2c.png">

开发者的环境是Windows，使用的composer v2.0.11；目标服务器环境是Linux；部署采用手动上传本地开发文件zip包格式（服务端解压缩），当上传完毕在服务端解压缩部署时，收到「腾讯云」短信告警，其提示存在“木马文件”CertificateDownloader.php

**Comment by xy-peng** [comment]
根据 @TheNorthMemory 分析，是之前版本 composer 在 Windows 环境下生成可执行文件时使用了 `eval()`，被检出风险。 

建议使用高版本（>= 2.1.10 ) 的 composer。

相关信息可以参考：
+ https://github.com/composer/composer/pull/9713
+ https://github.com/composer/composer/issues/9325
