### ISSUE TITLE
支持swoole环境吗？

### ISSUE THREAD

**Issue by MichonneHsu** [wechatpay-apiv3/wechatpay-php#96]
如题

**Comment by xy-peng** [comment]
简而言之，支持。

具体参考之前在 [wechatpay-guzzle-middle 的相关 issue](https://github.com/wechatpay-apiv3/wechatpay-guzzle-middleware/issues/36) 讨论 。在常见问题中也有[简单说明](https://github.com/wechatpay-apiv3/wechatpay-php#%E9%85%8D%E5%90%88swoole%E4%BD%BF%E7%94%A8%E6%97%B6%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E6%8E%A5%E5%8F%A3%E6%8A%A5%E9%94%99]。

**Comment by MichonneHsu** [comment]
> 简而言之，支持。
> 
> 具体参考之前在 [wechatpay-guzzle-middle 的相关 issue](https://github.com/wechatpay-apiv3/wechatpay-guzzle-middleware/issues/36) 讨论 。在常见问题中也有[简单说明](https://github.com/wechatpay-apiv3/wechatpay-php#%E9%85%8D%E5%90%88swoole%E4%BD%BF%E7%94%A8%E6%97%B6%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E6%8E%A5%E5%8F%A3%E6%8A%A5%E9%94%99)。

我看别的都是框架都是再次封装支付的，所以我寻思着是不是原生的支付代码不行。
